In [1]:
#cleaning the data of  the catogiries list

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('catogries_data.csv')#loading the data in the notebook file

In [5]:
df.head()

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,Entertainment,MrBeast,500000000.0,7.000000e+08,900000000.0,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10,abc
1,Gaming,PewDiePie,400000000.0,5.500000e+08,700000000.0,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10,xyz
2,Music,T-Series,800000000.0,1.000000e+09,NaN,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,test
3,Education,Khan Academy,150000000.0,2.000000e+08,250000000.0,NaN,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,abc
4,Tech,Marques Brownlee,120000000.0,1.600000e+08,200000000.0,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10,xyz

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       17 non-null     object
 1   Top_Creator    17 non-null     object
 2   Subs_2020      17 non-null     float64
 3   Subs_2021      17 non-null     float64
 4   Subs_2022      15 non-null     float64
 5   Subs_2023      16 non-null     float64
 6   Subs_2024      16 non-null     float64
 7   Views_2020     17 non-null     float64
 8   Views_2021     17 non-null     float64
 9   Views_2022     17 non-null     float64
 10  Views_2023     17 non-null     float64
 11  Views_2024     17 non-null     float64
 12  Random_Column  17 non-null     object
dtypes: float64(10), object(3)
memory usage: 2.0+ KB

In [7]:
df.describe()

,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024
count,1.700000e+01,1.700000e+01,1.500000e+01,1.600000e+01,1.600000e+01,1.700000e+01,1.700000e+01,1.700000e+01,1.700000e+01,1.700000e+01
mean,2.735295e+08,3.688237e+08,3.726669e+08,5.943753e+08,7.187504e+08,1.905882e+10,2.747059e+10,3.652941e+10,4.600000e+10,5.764706e+10
std,2.587696e+08,3.274499e+08,3.092953e+08,4.859896e+08,5.576359e+08,1.997333e+10,2.681212e+10,3.472772e+10,4.303922e+10,5.358281e+10
min,5.000000e+02,6.000000e+02,7.000000e+02,8.000000e+02,9.000000e+02,1.000000e+03,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03
25%,1.000000e+08,1.500000e+08,1.800000e+08,2.225000e+08,2.875000e+08,5.000000e+09,8.000000e+09,1.000000e+10,1.300000e+10,1.800000e+10
50%,1.500000e+08,2.000000e+08,2.500000e+08,4.250000e+08,5.250000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10
75%,4.000000e+08,5.500000e+08,5.500000e+08,9.500000e+08,1.225000e+09,2.500000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10
max,8.000000e+08,1.000000e+09,1.000000e+09,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       17 non-null     object
 1   Top_Creator    17 non-null     object
 2   Subs_2020      17 non-null     float64
 3   Subs_2021      17 non-null     float64
 4   Subs_2022      15 non-null     float64
 5   Subs_2023      16 non-null     float64
 6   Subs_2024      16 non-null     float64
 7   Views_2020     17 non-null     float64
 8   Views_2021     17 non-null     float64
 9   Views_2022     17 non-null     float64
 10  Views_2023     17 non-null     float64
 11  Views_2024     17 non-null     float64
 12  Random_Column  17 non-null     object
dtypes: float64(10), object(3)
memory usage: 2.0+ KB

In [11]:
df.head()

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,Entertainment,MrBeast,500000000.0,7.000000e+08,900000000.0,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10,abc
1,Gaming,PewDiePie,400000000.0,5.500000e+08,700000000.0,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10,xyz
2,Music,T-Series,800000000.0,1.000000e+09,NaN,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,test
3,Education,Khan Academy,150000000.0,2.000000e+08,250000000.0,NaN,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,abc
4,Tech,Marques Brownlee,120000000.0,1.600000e+08,200000000.0,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10,xyz

In [12]:
df.tail()

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
13,Eduaction,Khan Academy,150000000.0,200000000.0,2.500000e+08,3.000000e+08,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,typo
14,Shorts Creators,Zach King,200000000.0,350000000.0,6.000000e+08,9.000000e+08,1.200000e+09,2.000000e+10,4.000000e+10,7.000000e+10,1.000000e+11,1.300000e+11,abc
15,Kids,Cocomelon,600000000.0,800000000.0,1.000000e+09,1.200000e+09,1.400000e+09,5.000000e+10,7.000000e+10,9.000000e+10,1.100000e+11,1.300000e+11,xyz
16,Podcasts,Joe Rogan Clips,50000000.0,90000000.0,1.300000e+08,1.800000e+08,2.500000e+08,3.000000e+09,6.000000e+09,9.000000e+09,1.300000e+10,1.800000e+10,test
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.describe()

,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024
count,1.700000e+01,1.700000e+01,1.500000e+01,1.600000e+01,1.600000e+01,1.700000e+01,1.700000e+01,1.700000e+01,1.700000e+01,1.700000e+01
mean,2.735295e+08,3.688237e+08,3.726669e+08,5.943753e+08,7.187504e+08,1.905882e+10,2.747059e+10,3.652941e+10,4.600000e+10,5.764706e+10
std,2.587696e+08,3.274499e+08,3.092953e+08,4.859896e+08,5.576359e+08,1.997333e+10,2.681212e+10,3.472772e+10,4.303922e+10,5.358281e+10
min,5.000000e+02,6.000000e+02,7.000000e+02,8.000000e+02,9.000000e+02,1.000000e+03,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03
25%,1.000000e+08,1.500000e+08,1.800000e+08,2.225000e+08,2.875000e+08,5.000000e+09,8.000000e+09,1.000000e+10,1.300000e+10,1.800000e+10
50%,1.500000e+08,2.000000e+08,2.500000e+08,4.250000e+08,5.250000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10
75%,4.000000e+08,5.500000e+08,5.500000e+08,9.500000e+08,1.225000e+09,2.500000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10
max,8.000000e+08,1.000000e+09,1.000000e+09,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       17 non-null     object
 1   Top_Creator    17 non-null     object
 2   Subs_2020      17 non-null     float64
 3   Subs_2021      17 non-null     float64
 4   Subs_2022      15 non-null     float64
 5   Subs_2023      16 non-null     float64
 6   Subs_2024      16 non-null     float64
 7   Views_2020     17 non-null     float64
 8   Views_2021     17 non-null     float64
 9   Views_2022     17 non-null     float64
 10  Views_2023     17 non-null     float64
 11  Views_2024     17 non-null     float64
 12  Random_Column  17 non-null     object
dtypes: float64(10), object(3)
memory usage: 2.0+ KB

In [15]:
df.isnull()

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,True,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,True,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,True,True,True,True,True,True,True,True,True,True,True,True,True

In [16]:
df.isnull().sum()

Category         1
Top_Creator      1
Subs_2020        1
Subs_2021        1
Subs_2022        3
Subs_2023        2
Subs_2024        2
Views_2020       1
Views_2021       1
Views_2022       1
Views_2023       1
Views_2024       1
Random_Column    1
dtype: int64

In [18]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
dtype: bool

In [32]:
df.dropna(inplace=True)

In [33]:
df

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024
0,Entertainment,MrBeast,500000000.0,700000000.0,9.000000e+08,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10
1,Gaming,PewDiePie,400000000.0,550000000.0,7.000000e+08,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10
4,Tech,Marques Brownlee,120000000.0,160000000.0,2.000000e+08,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10
5,Vlogs,Casey Neistat,300000000.0,400000000.0,5.000000e+08,6.500000e+08,8.000000e+08,2.000000e+10,3.000000e+10,4.000000e+10,5.000000e+10,6.500000e+10
7,Finance,Graham Stephan,80000000.0,120000000.0,1.600000e+08,2.000000e+08,2.500000e+08,4.000000e+09,7.000000e+09,9.000000e+09,1.200000e+10,1.600000e+10
8,Food,Mark Wiens,150000000.0,200000000.0,2.500000e+08,3.000000e+08,3.500000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10
9,Comedy,Dude Perfect,250000000.0,350000000.0,4.500000e+08,5.500000e+08,6.500000e+08,1.500000e+10,2.500000e+10,3.500000e+10,4.500000e+10,5.500000e+10
10,Unknown,Random Guy,1000.0,2000.0,3.000000e+03,4.000000e+03,5.000000e+03,1.000000e+04,2.000000e+04,3.000000e+04,4.000000e+04,5.000000e+04
11,FakeCategory,NoOne,500.0,600.0,7.000000e+02,8.000000e+02,9.000000e+02,1.000000e+03,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03
13,Eduaction,Khan Academy,150000000.0,200000000.0,2.500000e+08,3.000000e+08,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10
14,Shorts Creators,Zach King,200000000.0,350000000.0,6.000000e+08,9.000000e+08,1.200000e+09,2.000000e+10,4.000000e+10,7.000000e+10,1.000000e+11,1.300000e+11
15,Kids,Cocomelon,600000000.0,800000000.0,1.000000e+09,1.200000e+09,1.400000e+09,5.000000e+10,7.000000e+10,9.000000e+10,1.100000e+11,1.300000e+11
16,Podcasts,Joe Rogan Clips,50000000.0,90000000.0,1.300000e+08,1.800000e+08,2.500000e+08,3.000000e+09,6.000000e+09,9.000000e+09,1.300000e+10,1.800000e+10