In [1]:
#cleaning the data of  the catogiries list

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('catogries_data.csv')#loading the data in the notebook file

In [5]:
df.head()

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,Entertainment,MrBeast,500000000.0,7.000000e+08,900000000.0,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10,abc
1,Gaming,PewDiePie,400000000.0,5.500000e+08,700000000.0,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10,xyz
2,Music,T-Series,800000000.0,1.000000e+09,NaN,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,test
3,Education,Khan Academy,150000000.0,2.000000e+08,250000000.0,NaN,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,abc
4,Tech,Marques Brownlee,120000000.0,1.600000e+08,200000000.0,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10,xyz

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       17 non-null     object
 1   Top_Creator    17 non-null     object
 2   Subs_2020      17 non-null     float64
 3   Subs_2021      17 non-null     float64
 4   Subs_2022      15 non-null     float64
 5   Subs_2023      16 non-null     float64
 6   Subs_2024      16 non-null     float64
 7   Views_2020     17 non-null     float64
 8   Views_2021     17 non-null     float64
 9   Views_2022     17 non-null     float64
 10  Views_2023     17 non-null     float64
 11  Views_2024     17 non-null     float64
 12  Random_Column  17 non-null     object
dtypes: float64(10), object(3)
memory usage: 2.0+ KB

In [7]:
df.describe()

,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024
count,1.700000e+01,1.700000e+01,1.500000e+01,1.600000e+01,1.600000e+01,1.700000e+01,1.700000e+01,1.700000e+01,1.700000e+01,1.700000e+01
mean,2.735295e+08,3.688237e+08,3.726669e+08,5.943753e+08,7.187504e+08,1.905882e+10,2.747059e+10,3.652941e+10,4.600000e+10,5.764706e+10
std,2.587696e+08,3.274499e+08,3.092953e+08,4.859896e+08,5.576359e+08,1.997333e+10,2.681212e+10,3.472772e+10,4.303922e+10,5.358281e+10
min,5.000000e+02,6.000000e+02,7.000000e+02,8.000000e+02,9.000000e+02,1.000000e+03,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03
25%,1.000000e+08,1.500000e+08,1.800000e+08,2.225000e+08,2.875000e+08,5.000000e+09,8.000000e+09,1.000000e+10,1.300000e+10,1.800000e+10
50%,1.500000e+08,2.000000e+08,2.500000e+08,4.250000e+08,5.250000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10
75%,4.000000e+08,5.500000e+08,5.500000e+08,9.500000e+08,1.225000e+09,2.500000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10
max,8.000000e+08,1.000000e+09,1.000000e+09,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       17 non-null     object
 1   Top_Creator    17 non-null     object
 2   Subs_2020      17 non-null     float64
 3   Subs_2021      17 non-null     float64
 4   Subs_2022      15 non-null     float64
 5   Subs_2023      16 non-null     float64
 6   Subs_2024      16 non-null     float64
 7   Views_2020     17 non-null     float64
 8   Views_2021     17 non-null     float64
 9   Views_2022     17 non-null     float64
 10  Views_2023     17 non-null     float64
 11  Views_2024     17 non-null     float64
 12  Random_Column  17 non-null     object
dtypes: float64(10), object(3)
memory usage: 2.0+ KB

In [9]:
df.head()

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,Entertainment,MrBeast,500000000.0,7.000000e+08,900000000.0,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10,abc
1,Gaming,PewDiePie,400000000.0,5.500000e+08,700000000.0,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10,xyz
2,Music,T-Series,800000000.0,1.000000e+09,NaN,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,test
3,Education,Khan Academy,150000000.0,2.000000e+08,250000000.0,NaN,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,abc
4,Tech,Marques Brownlee,120000000.0,1.600000e+08,200000000.0,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10,xyz

In [10]:
df.tail()

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
13,Eduaction,Khan Academy,150000000.0,200000000.0,2.500000e+08,3.000000e+08,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,typo
14,Shorts Creators,Zach King,200000000.0,350000000.0,6.000000e+08,9.000000e+08,1.200000e+09,2.000000e+10,4.000000e+10,7.000000e+10,1.000000e+11,1.300000e+11,abc
15,Kids,Cocomelon,600000000.0,800000000.0,1.000000e+09,1.200000e+09,1.400000e+09,5.000000e+10,7.000000e+10,9.000000e+10,1.100000e+11,1.300000e+11,xyz
16,Podcasts,Joe Rogan Clips,50000000.0,90000000.0,1.300000e+08,1.800000e+08,2.500000e+08,3.000000e+09,6.000000e+09,9.000000e+09,1.300000e+10,1.800000e+10,test
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.describe()

,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024
count,1.700000e+01,1.700000e+01,1.500000e+01,1.600000e+01,1.600000e+01,1.700000e+01,1.700000e+01,1.700000e+01,1.700000e+01,1.700000e+01
mean,2.735295e+08,3.688237e+08,3.726669e+08,5.943753e+08,7.187504e+08,1.905882e+10,2.747059e+10,3.652941e+10,4.600000e+10,5.764706e+10
std,2.587696e+08,3.274499e+08,3.092953e+08,4.859896e+08,5.576359e+08,1.997333e+10,2.681212e+10,3.472772e+10,4.303922e+10,5.358281e+10
min,5.000000e+02,6.000000e+02,7.000000e+02,8.000000e+02,9.000000e+02,1.000000e+03,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03
25%,1.000000e+08,1.500000e+08,1.800000e+08,2.225000e+08,2.875000e+08,5.000000e+09,8.000000e+09,1.000000e+10,1.300000e+10,1.800000e+10
50%,1.500000e+08,2.000000e+08,2.500000e+08,4.250000e+08,5.250000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10
75%,4.000000e+08,5.500000e+08,5.500000e+08,9.500000e+08,1.225000e+09,2.500000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10
max,8.000000e+08,1.000000e+09,1.000000e+09,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       17 non-null     object
 1   Top_Creator    17 non-null     object
 2   Subs_2020      17 non-null     float64
 3   Subs_2021      17 non-null     float64
 4   Subs_2022      15 non-null     float64
 5   Subs_2023      16 non-null     float64
 6   Subs_2024      16 non-null     float64
 7   Views_2020     17 non-null     float64
 8   Views_2021     17 non-null     float64
 9   Views_2022     17 non-null     float64
 10  Views_2023     17 non-null     float64
 11  Views_2024     17 non-null     float64
 12  Random_Column  17 non-null     object
dtypes: float64(10), object(3)
memory usage: 2.0+ KB

In [13]:
df.isnull()

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,True,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,True,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,True,True,True,True,True,True,True,True,True,True,True,True,True

In [14]:
df.isnull().sum()

Category         1
Top_Creator      1
Subs_2020        1
Subs_2021        1
Subs_2022        3
Subs_2023        2
Subs_2024        2
Views_2020       1
Views_2021       1
Views_2022       1
Views_2023       1
Views_2024       1
Random_Column    1
dtype: int64

In [15]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
dtype: bool

In [16]:
df

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,Entertainment,MrBeast,500000000.0,7.000000e+08,9.000000e+08,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10,abc
1,Gaming,PewDiePie,400000000.0,5.500000e+08,7.000000e+08,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10,xyz
2,Music,T-Series,800000000.0,1.000000e+09,NaN,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,test
3,Education,Khan Academy,150000000.0,2.000000e+08,2.500000e+08,NaN,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,abc
4,Tech,Marques Brownlee,120000000.0,1.600000e+08,2.000000e+08,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10,xyz
5,Vlogs,Casey Neistat,300000000.0,4.000000e+08,5.000000e+08,6.500000e+08,8.000000e+08,2.000000e+10,3.000000e+10,4.000000e+10,5.000000e+10,6.500000e+10,test
6,Fitness,Chloe Ting,100000000.0,1.500000e+08,2.000000e+08,2.300000e+08,NaN,5.000000e+09,8.000000e+09,1.000000e+10,1.200000e+10,1.500000e+10,abc
7,Finance,Graham Stephan,80000000.0,1.200000e+08,1.600000e+08,2.000000e+08,2.500000e+08,4.000000e+09,7.000000e+09,9.000000e+09,1.200000e+10,1.600000e+10,xyz
8,Food,Mark Wiens,150000000.0,2.000000e+08,2.500000e+08,3.000000e+08,3.500000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,test
9,Comedy,Dude Perfect,250000000.0,3.500000e+08,4.500000e+08,5.500000e+08,6.500000e+08,1.500000e+10,2.500000e+10,3.500000e+10,4.500000e+10,5.500000e+10,abc
10,Unknown,Random Guy,1000.0,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03,1.000000e+04,2.000000e+04,3.000000e+04,4.000000e+04,5.000000e+04,noise
11,FakeCategory,NoOne,500.0,6.000000e+02,7.000000e+02,8.000000e+02,9.000000e+02,1.000000e+03,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03,noise
12,Music,T-Series,800000000.0,1.000000e+09,NaN,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,duplicate
13,Eduaction,Khan Academy,150000000.0,2.000000e+08,2.500000e+08,3.000000e+08,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,typo
14,Shorts Creators,Zach King,200000000.0,3.500000e+08,6.000000e+08,9.000000e+08,1.200000e+09,2.000000e+10,4.000000e+10,7.000000e+10,1.000000e+11,1.300000e+11,abc
15,Kids,Cocomelon,600000000.0,8.000000e+08,1.000000e+09,1.200000e+09,1.400000e+09,5.000000e+10,7.000000e+10,9.000000e+10,1.100000e+11,1.300000e+11,xyz
16,Podcasts,Joe Rogan Clips,50000000.0,9.000000e+07,1.300000e+08,1.800000e+08,2.500000e+08,3.000000e+09,6.000000e+09,9.000000e+09,1.300000e+10,1.800000e+10,test
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,Entertainment,MrBeast,500000000.0,7.000000e+08,9.000000e+08,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10,abc
1,Gaming,PewDiePie,400000000.0,5.500000e+08,7.000000e+08,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10,xyz
2,Music,T-Series,800000000.0,1.000000e+09,NaN,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,test
3,Education,Khan Academy,150000000.0,2.000000e+08,2.500000e+08,NaN,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,abc
4,Tech,Marques Brownlee,120000000.0,1.600000e+08,2.000000e+08,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10,xyz
5,Vlogs,Casey Neistat,300000000.0,4.000000e+08,5.000000e+08,6.500000e+08,8.000000e+08,2.000000e+10,3.000000e+10,4.000000e+10,5.000000e+10,6.500000e+10,test
6,Fitness,Chloe Ting,100000000.0,1.500000e+08,2.000000e+08,2.300000e+08,NaN,5.000000e+09,8.000000e+09,1.000000e+10,1.200000e+10,1.500000e+10,abc
7,Finance,Graham Stephan,80000000.0,1.200000e+08,1.600000e+08,2.000000e+08,2.500000e+08,4.000000e+09,7.000000e+09,9.000000e+09,1.200000e+10,1.600000e+10,xyz
8,Food,Mark Wiens,150000000.0,2.000000e+08,2.500000e+08,3.000000e+08,3.500000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,test
9,Comedy,Dude Perfect,250000000.0,3.500000e+08,4.500000e+08,5.500000e+08,6.500000e+08,1.500000e+10,2.500000e+10,3.500000e+10,4.500000e+10,5.500000e+10,abc
10,Unknown,Random Guy,1000.0,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03,1.000000e+04,2.000000e+04,3.000000e+04,4.000000e+04,5.000000e+04,noise
11,FakeCategory,NoOne,500.0,6.000000e+02,7.000000e+02,8.000000e+02,9.000000e+02,1.000000e+03,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03,noise
12,Music,T-Series,800000000.0,1.000000e+09,NaN,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,duplicate
13,Eduaction,Khan Academy,150000000.0,2.000000e+08,2.500000e+08,3.000000e+08,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,typo
14,Shorts Creators,Zach King,200000000.0,3.500000e+08,6.000000e+08,9.000000e+08,1.200000e+09,2.000000e+10,4.000000e+10,7.000000e+10,1.000000e+11,1.300000e+11,abc
15,Kids,Cocomelon,600000000.0,8.000000e+08,1.000000e+09,1.200000e+09,1.400000e+09,5.000000e+10,7.000000e+10,9.000000e+10,1.100000e+11,1.300000e+11,xyz
16,Podcasts,Joe Rogan Clips,50000000.0,9.000000e+07,1.300000e+08,1.800000e+08,2.500000e+08,3.000000e+09,6.000000e+09,9.000000e+09,1.300000e+10,1.800000e+10,test
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
np.argmax(df['Subs_2024'])

np.int64(2)

In [19]:
df.index

RangeIndex(start=0, stop=18, step=1)

In [20]:
df.columns

Index(['Category', 'Top_Creator', 'Subs_2020', 'Subs_2021', 'Subs_2022',
       'Subs_2023', 'Subs_2024', 'Views_2020', 'Views_2021', 'Views_2022',
       'Views_2023', 'Views_2024', 'Random_Column'],
      dtype='object')

In [21]:
df['Category']

0       Entertainment
1              Gaming
2               Music
3           Education
4                Tech
5               Vlogs
6             Fitness
7             Finance
8                Food
9              Comedy
10            Unknown
11       FakeCategory
12              Music
13          Eduaction
14    Shorts Creators
15               Kids
16           Podcasts
17                NaN
Name: Category, dtype: object

In [22]:
df.loc[:,['Category','Top_Creator']]

           Category       Top_Creator
0     Entertainment           MrBeast
1            Gaming         PewDiePie
2             Music          T-Series
3         Education      Khan Academy
4              Tech  Marques Brownlee
5             Vlogs     Casey Neistat
6           Fitness        Chloe Ting
7           Finance    Graham Stephan
8              Food        Mark Wiens
9            Comedy      Dude Perfect
10          Unknown        Random Guy
11     FakeCategory             NoOne
12            Music          T-Series
13        Eduaction      Khan Academy
14  Shorts Creators         Zach King
15             Kids         Cocomelon
16         Podcasts   Joe Rogan Clips
17              NaN               NaN

In [23]:
df[0:10]

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,Entertainment,MrBeast,500000000.0,7.000000e+08,900000000.0,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10,abc
1,Gaming,PewDiePie,400000000.0,5.500000e+08,700000000.0,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10,xyz
2,Music,T-Series,800000000.0,1.000000e+09,NaN,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,test
3,Education,Khan Academy,150000000.0,2.000000e+08,250000000.0,NaN,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,abc
4,Tech,Marques Brownlee,120000000.0,1.600000e+08,200000000.0,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10,xyz
5,Vlogs,Casey Neistat,300000000.0,4.000000e+08,500000000.0,6.500000e+08,8.000000e+08,2.000000e+10,3.000000e+10,4.000000e+10,5.000000e+10,6.500000e+10,test
6,Fitness,Chloe Ting,100000000.0,1.500000e+08,200000000.0,2.300000e+08,NaN,5.000000e+09,8.000000e+09,1.000000e+10,1.200000e+10,1.500000e+10,abc
7,Finance,Graham Stephan,80000000.0,1.200000e+08,160000000.0,2.000000e+08,2.500000e+08,4.000000e+09,7.000000e+09,9.000000e+09,1.200000e+10,1.600000e+10,xyz
8,Food,Mark Wiens,150000000.0,2.000000e+08,250000000.0,3.000000e+08,3.500000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,test
9,Comedy,Dude Perfect,250000000.0,3.500000e+08,450000000.0,5.500000e+08,6.500000e+08,1.500000e+10,2.500000e+10,3.500000e+10,4.500000e+10,5.500000e+10,abc

In [24]:
df.isnull()

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,True,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,True,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,True,True,True,True,True,True,True,True,True,True,True,True,True

In [25]:
df.isnull().sum()

Category         1
Top_Creator      1
Subs_2020        1
Subs_2021        1
Subs_2022        3
Subs_2023        2
Subs_2024        2
Views_2020       1
Views_2021       1
Views_2022       1
Views_2023       1
Views_2024       1
Random_Column    1
dtype: int64

In [26]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
dtype: bool

In [30]:
df.fillna(0,inplace=True)

In [31]:
df

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,Entertainment,MrBeast,500000000.0,7.000000e+08,9.000000e+08,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10,abc
1,Gaming,PewDiePie,400000000.0,5.500000e+08,7.000000e+08,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10,xyz
2,Music,T-Series,800000000.0,1.000000e+09,0.000000e+00,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,test
3,Education,Khan Academy,150000000.0,2.000000e+08,2.500000e+08,0.000000e+00,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,abc
4,Tech,Marques Brownlee,120000000.0,1.600000e+08,2.000000e+08,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10,xyz
5,Vlogs,Casey Neistat,300000000.0,4.000000e+08,5.000000e+08,6.500000e+08,8.000000e+08,2.000000e+10,3.000000e+10,4.000000e+10,5.000000e+10,6.500000e+10,test
6,Fitness,Chloe Ting,100000000.0,1.500000e+08,2.000000e+08,2.300000e+08,0.000000e+00,5.000000e+09,8.000000e+09,1.000000e+10,1.200000e+10,1.500000e+10,abc
7,Finance,Graham Stephan,80000000.0,1.200000e+08,1.600000e+08,2.000000e+08,2.500000e+08,4.000000e+09,7.000000e+09,9.000000e+09,1.200000e+10,1.600000e+10,xyz
8,Food,Mark Wiens,150000000.0,2.000000e+08,2.500000e+08,3.000000e+08,3.500000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,test
9,Comedy,Dude Perfect,250000000.0,3.500000e+08,4.500000e+08,5.500000e+08,6.500000e+08,1.500000e+10,2.500000e+10,3.500000e+10,4.500000e+10,5.500000e+10,abc
10,Unknown,Random Guy,1000.0,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03,1.000000e+04,2.000000e+04,3.000000e+04,4.000000e+04,5.000000e+04,noise
11,FakeCategory,NoOne,500.0,6.000000e+02,7.000000e+02,8.000000e+02,9.000000e+02,1.000000e+03,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03,noise
12,Music,T-Series,800000000.0,1.000000e+09,0.000000e+00,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,duplicate
13,Eduaction,Khan Academy,150000000.0,2.000000e+08,2.500000e+08,3.000000e+08,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,typo
14,Shorts Creators,Zach King,200000000.0,3.500000e+08,6.000000e+08,9.000000e+08,1.200000e+09,2.000000e+10,4.000000e+10,7.000000e+10,1.000000e+11,1.300000e+11,abc
15,Kids,Cocomelon,600000000.0,8.000000e+08,1.000000e+09,1.200000e+09,1.400000e+09,5.000000e+10,7.000000e+10,9.000000e+10,1.100000e+11,1.300000e+11,xyz
16,Podcasts,Joe Rogan Clips,50000000.0,9.000000e+07,1.300000e+08,1.800000e+08,2.500000e+08,3.000000e+09,6.000000e+09,9.000000e+09,1.300000e+10,1.800000e+10,test
17,0,0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0

In [36]:
df.sort_values(['Subs_2020','Subs_2021','Subs_2022','Subs_2023','Subs_2024'],ascending=False,inplace=True)

In [37]:
df

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
2,Music,T-Series,800000000.0,1.000000e+09,0.000000e+00,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,test
12,Music,T-Series,800000000.0,1.000000e+09,0.000000e+00,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,duplicate
15,Kids,Cocomelon,600000000.0,8.000000e+08,1.000000e+09,1.200000e+09,1.400000e+09,5.000000e+10,7.000000e+10,9.000000e+10,1.100000e+11,1.300000e+11,xyz
0,Entertainment,MrBeast,500000000.0,7.000000e+08,9.000000e+08,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10,abc
1,Gaming,PewDiePie,400000000.0,5.500000e+08,7.000000e+08,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10,xyz
5,Vlogs,Casey Neistat,300000000.0,4.000000e+08,5.000000e+08,6.500000e+08,8.000000e+08,2.000000e+10,3.000000e+10,4.000000e+10,5.000000e+10,6.500000e+10,test
9,Comedy,Dude Perfect,250000000.0,3.500000e+08,4.500000e+08,5.500000e+08,6.500000e+08,1.500000e+10,2.500000e+10,3.500000e+10,4.500000e+10,5.500000e+10,abc
14,Shorts Creators,Zach King,200000000.0,3.500000e+08,6.000000e+08,9.000000e+08,1.200000e+09,2.000000e+10,4.000000e+10,7.000000e+10,1.000000e+11,1.300000e+11,abc
13,Eduaction,Khan Academy,150000000.0,2.000000e+08,2.500000e+08,3.000000e+08,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,typo
8,Food,Mark Wiens,150000000.0,2.000000e+08,2.500000e+08,3.000000e+08,3.500000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,test
3,Education,Khan Academy,150000000.0,2.000000e+08,2.500000e+08,0.000000e+00,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,abc
4,Tech,Marques Brownlee,120000000.0,1.600000e+08,2.000000e+08,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10,xyz
6,Fitness,Chloe Ting,100000000.0,1.500000e+08,2.000000e+08,2.300000e+08,0.000000e+00,5.000000e+09,8.000000e+09,1.000000e+10,1.200000e+10,1.500000e+10,abc
7,Finance,Graham Stephan,80000000.0,1.200000e+08,1.600000e+08,2.000000e+08,2.500000e+08,4.000000e+09,7.000000e+09,9.000000e+09,1.200000e+10,1.600000e+10,xyz
16,Podcasts,Joe Rogan Clips,50000000.0,9.000000e+07,1.300000e+08,1.800000e+08,2.500000e+08,3.000000e+09,6.000000e+09,9.000000e+09,1.300000e+10,1.800000e+10,test
10,Unknown,Random Guy,1000.0,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03,1.000000e+04,2.000000e+04,3.000000e+04,4.000000e+04,5.000000e+04,noise
11,FakeCategory,NoOne,500.0,6.000000e+02,7.000000e+02,8.000000e+02,9.000000e+02,1.000000e+03,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03,noise
17,0,0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0

In [40]:
df.reset_index(drop=True,inplace=True)

In [41]:
df

,Category,Top_Creator,Subs_2020,Subs_2021,Subs_2022,Subs_2023,Subs_2024,Views_2020,Views_2021,Views_2022,Views_2023,Views_2024,Random_Column
0,Music,T-Series,800000000.0,1.000000e+09,0.000000e+00,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,test
1,Music,T-Series,800000000.0,1.000000e+09,0.000000e+00,1.400000e+09,1.600000e+09,6.000000e+10,8.000000e+10,1.000000e+11,1.200000e+11,1.500000e+11,duplicate
2,Kids,Cocomelon,600000000.0,8.000000e+08,1.000000e+09,1.200000e+09,1.400000e+09,5.000000e+10,7.000000e+10,9.000000e+10,1.100000e+11,1.300000e+11,xyz
3,Entertainment,MrBeast,500000000.0,7.000000e+08,9.000000e+08,1.100000e+09,1.300000e+09,3.000000e+10,4.000000e+10,5.500000e+10,7.000000e+10,9.000000e+10,abc
4,Gaming,PewDiePie,400000000.0,5.500000e+08,7.000000e+08,8.500000e+08,1.000000e+09,2.500000e+10,3.500000e+10,4.500000e+10,6.000000e+10,7.500000e+10,xyz
5,Vlogs,Casey Neistat,300000000.0,4.000000e+08,5.000000e+08,6.500000e+08,8.000000e+08,2.000000e+10,3.000000e+10,4.000000e+10,5.000000e+10,6.500000e+10,test
6,Comedy,Dude Perfect,250000000.0,3.500000e+08,4.500000e+08,5.500000e+08,6.500000e+08,1.500000e+10,2.500000e+10,3.500000e+10,4.500000e+10,5.500000e+10,abc
7,Shorts Creators,Zach King,200000000.0,3.500000e+08,6.000000e+08,9.000000e+08,1.200000e+09,2.000000e+10,4.000000e+10,7.000000e+10,1.000000e+11,1.300000e+11,abc
8,Eduaction,Khan Academy,150000000.0,2.000000e+08,2.500000e+08,3.000000e+08,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,typo
9,Food,Mark Wiens,150000000.0,2.000000e+08,2.500000e+08,3.000000e+08,3.500000e+08,9.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,test
10,Education,Khan Academy,150000000.0,2.000000e+08,2.500000e+08,0.000000e+00,4.000000e+08,8.000000e+09,1.200000e+10,1.500000e+10,1.800000e+10,2.200000e+10,abc
11,Tech,Marques Brownlee,120000000.0,1.600000e+08,2.000000e+08,2.500000e+08,3.000000e+08,7.000000e+09,1.000000e+10,1.300000e+10,1.600000e+10,2.000000e+10,xyz
12,Fitness,Chloe Ting,100000000.0,1.500000e+08,2.000000e+08,2.300000e+08,0.000000e+00,5.000000e+09,8.000000e+09,1.000000e+10,1.200000e+10,1.500000e+10,abc
13,Finance,Graham Stephan,80000000.0,1.200000e+08,1.600000e+08,2.000000e+08,2.500000e+08,4.000000e+09,7.000000e+09,9.000000e+09,1.200000e+10,1.600000e+10,xyz
14,Podcasts,Joe Rogan Clips,50000000.0,9.000000e+07,1.300000e+08,1.800000e+08,2.500000e+08,3.000000e+09,6.000000e+09,9.000000e+09,1.300000e+10,1.800000e+10,test
15,Unknown,Random Guy,1000.0,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03,1.000000e+04,2.000000e+04,3.000000e+04,4.000000e+04,5.000000e+04,noise
16,FakeCategory,NoOne,500.0,6.000000e+02,7.000000e+02,8.000000e+02,9.000000e+02,1.000000e+03,2.000000e+03,3.000000e+03,4.000000e+03,5.000000e+03,noise
17,0,0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0