In [1]:
# here we are going to  analyise the data and get the proper key insghts what we can make

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('data.csv')
df

,Region,Sub_Region,Country,Continent_Group,Population_Million,Internet_Users_Million,YouTube_Users_Million,Avg_Daily_YouTube_Hours,Mobile_Internet_Percentage,Top_Content_Category,Average_Monthly_Views_Billion,Top_Creator,Top_Creator_Subs_Million,Language_Group,GDP_Per_Capita_USD
0,India,South Asia,India,Asia,1430,950,467,2.8,76,Entertainment,185,T-Series,290.0,Hindi,2500
1,Indonesia,Southeast Asia,Indonesia,Asia,280,212,139,2.5,78,Music,58,Ricis Official,48.0,Indonesian,4700
2,Pakistan,South Asia,Pakistan,Asia,245,132,71,2.1,63,Entertainment,23,Ducky Bhai,16.0,Urdu,1600
3,Bangladesh,South Asia,Bangladesh,Asia,173,105,53,2.0,71,Music,19,Tawhid Afridi,6.0,Bengali,2900
4,Japan,East Asia,Japan,Asia,124,118,102,1.7,92,Gaming,44,HikakinTV,13.0,Japanese,34000
5,South Korea,East Asia,South Korea,Asia,52,50,46,2.4,97,K-Pop,39,BLACKPINK,96.0,Korean,36000
6,China,East Asia,China,Asia,1410,1080,350,1.1,96,Short Video,120,No Official YouTube Dominance,NaN,Mandarin,12600
7,Philippines,Southeast Asia,Philippines,Asia,118,86,58,3.3,74,Vlogs,32,Cong TV,12.0,Filipino,3900
8,Thailand,Southeast Asia,Thailand,Asia,71,61,54,2.3,84,Entertainment,25,Bie The Ska,15.0,Thai,7800
9,Vietnam,Southeast Asia,Vietnam,Asia,101,79,63,2.0,79,Music,27,FAPTV,14.0,Vietnamese,4300
10,Malaysia,Southeast Asia,Malaysia,Asia,35,33,29,2.1,91,Lifestyle,12,Les Copaque,16.0,Malay,12500
11,Nepal,South Asia,Nepal,Asia,31,19,11,1.7,55,Music,4,Sisan Baniya,2.0,Nepali,1400
12,Sri Lanka,South Asia,Sri Lanka,Asia,22,13,8,1.9,58,Education,3,SL VLOG,1.0,Sinhala,3900
13,Saudi Arabia,West Asia,Saudi Arabia,Asia,37,36,31,2.6,99,Lifestyle,16,Noor Stars,22.0,Arabic,32000
14,UAE,West Asia,UAE,Asia,10,10,9,2.2,99,Luxury/Lifestyle,5,Mo Vlogs,12.0,Arabic/English,47000
15,Turkey,West Asia,Turkey,Asia,86,74,58,2.3,83,Drama,28,Orkun Isitmak,12.0,Turkish,10600
16,Russia,Eastern Europe,Russia,Rest of World,146,130,95,1.9,85,News,42,A4,75.0,Russian,14000
17,USA,North America,United States,Rest of World,342,312,246,2.9,93,Entertainment,240,MrBeast,390.0,English,82000
18,Canada,North America,Canada,Rest of World,40,38,31,2.1,92,Education,11,Linus Tech Tips,16.0,English/French,54000
19,Mexico,North America,Mexico,Rest of World,131,104,83,2.7,77,Entertainment,51,Badabun,47.0,Spanish,13000
20,Brazil,South America,Brazil,Rest of World,216,181,144,2.8,81,Music,77,KondZilla,67.0,Portuguese,10300
21,Argentina,South America,Argentina,Rest of World,46,41,33,2.2,82,Gaming,12,VEGETTA777,34.0,Spanish,13700
22,UK,Europe,United Kingdom,Rest of World,69,66,57,2.0,95,Education,18,DanTDM,29.0,English,51000
23,Germany,Europe,Germany,Rest of World,84,79,65,1.8,94,Tech,21,Kurzgesagt,24.0,German,55000
24,France,Europe,France,Rest of World,65,61,52,1.9,92,Lifestyle,18,Squeezie,19.0,French,47000
25,Spain,Europe,Spain,Rest of World,48,45,39,2.1,91,Gaming,14,elrubiusOMG,41.0,Spanish,33000
26,Italy,Europe,Italy,Rest of World,59,54,45,1.7,89,Lifestyle,13,FavijTV,7.0,Italian,39000
27,Nigeria,Africa,Nigeria,Rest of World,229,122,68,2.5,69,Comedy,18,MarkAngelComedy,9.0,English,2400
28,South Africa,Africa,South Africa,Rest of World,63,47,32,2.1,73,Music,10,Waffles,2.0,English,6700
29,Egypt,Africa,Egypt,Rest of World,116,82,55,2.2,71,Entertainment,16,Ahmed Hassan,8.0,Arabic,4300
30,Australia,Oceania,Australia,Rest of World,27,26,22,1.9,96,Lifestyle,8,LazarBeam,22.0,English,65000
31,New Zealand,Oceania,New Zealand,Rest of World,5,5,4,1.8,95,Gaming,1,Shane Dawson,18.0,English,52000
32,Colombia,South America,Colombia,Rest of World,53,43,34,2.4,76,Music,13,Karen Polinesia,27.0,Spanish,6900
33,Chile,South America,Chile,Rest of World,20,18,15,2.0,88,Tech,5,German Garmendia,45.0,Spanish,16000
34,Peru,South America,Peru,Rest of World,35,27,20,2.1,73,Vlogs,7,Andynsane,4.0,Spanish,7200
35,Poland,Europe,Poland,Rest of World,38,34,28,1.8,89,Gaming,9,Blowek,5.0,Polish,22000
36,Netherlands,Europe,Netherlands,Rest of World,18,17,15,1.7,96,Tech,5,NikkieTutorials,14.0,Dutch,61000
37,Sweden,Europe,Sweden,Rest of World,11,11,9,1.9,97,Gaming,4,PewDiePie,110.0,Swedish/English,63000
38,Norway,Europe,Norway,Rest of World,6,6,5,1.7,98,Gaming,2,Noobwork,1.0,Norwegian,89000
39,Kenya,Africa,Kenya,Rest of World,57,34,21,2.0,67,Comedy,6,Thee Pluto,1.0,English/Swahili,2200
40,Morocco,Africa,Morocco,Rest of World,39,31,22,2.0,70,Entertainment,7,Ilyas Elmaliki,2.0,Arabic/French,3900

### DATA ANALYSIS

In [6]:
internet_average_usage = np.mean (df['Avg_Daily_YouTube_Hours'])
(internet_average_usage)

np.float64(2.126829268292683)

In [7]:
avg_views_world = np.mean(df['Average_Monthly_Views_Billion'])
avg_views_world

np.float64(30.926829268292682)

In [8]:
avg_int_users = np.mean(df['Internet_Users_Million'])
avg_int_users

np.float64(113.95121951219512)

In [9]:
#max subs in the world 
max_subs = np.argmax(df['Top_Creator_Subs_Million'])
max_subs
Top_creater = np.max(df['Top_Creator_Subs_Million'])
Top_creater
name = df.at[17,'Top_Creator']
name
print(f"The most famous youtube with over {Top_creater} Million Subs  is {name}")

The most famous youtube with over 390.0 Million Subs  is MrBeast

In [14]:
#Country and there most famous youtuber 
Top_creator = df[['Country','Top_Creator']]
#Top_creator

In [11]:
#country and their Internet users in millions 
Usage = df[['Country','Internet_Users_Million']]

# Asian creator data

In [16]:
asian_creator = df.loc[0:15]

In [42]:
#ASIAN MOST FAMOUS YOUTUBER 
np.argmax(asian_creator['Top_Creator_Subs_Million'])
top_creator = asian_creator.at[0,'Top_Creator']
Top_youtuber = print(f"The most youtube channel in india is {top_creater} with over {np.max(asian_creater['Top_Creator_Subs_Million'])}")

The most youtube channel in india is T-Series with over 290.0

In [43]:
#avg monthly views of the asia 
views = int(np.sum(asian_creator['Average_Monthly_Views_Billion']))
monthly_views = print(f'Average monthly views of the asia is {views} billion')

Average monthly views of the asia is 640 billion

In [44]:
#total  internet user of the asia 
internet_users = int(np.sum(asian_creator['Internet_Users_Million']))
Total_users = print(f'The Total internet users in Asia is {internet_users} Million')
Total_users

The Total internet users in Asia is 3058 Million

In [90]:
# coutries in the asia 
countries  =list( asian_creator['Region'])

countries_asia = print(f'The countries that are includes in asia region is {countries}')

The countries that are includes in asia region is ['India', 'Indonesia', 'Pakistan', 'Bangladesh', 'Japan', 'South Korea', 'China', 'Philippines', 'Thailand', 'Vietnam', 'Malaysia', 'Nepal', 'Sri Lanka', 'Saudi Arabia', 'UAE', 'Turkey']

In [93]:
#total population 
Total_P = int(np.sum(asian_creator['Population_Million']))
Total_poputtion  = print(f'Total popultation of the Asia is {Total_P} million')

Total popultation of the Asia is 4225 million

# Rest of the World

In [59]:
world_creator = df.loc[16:40]
world_creator

,Region,Sub_Region,Country,Continent_Group,Population_Million,Internet_Users_Million,YouTube_Users_Million,Avg_Daily_YouTube_Hours,Mobile_Internet_Percentage,Top_Content_Category,Average_Monthly_Views_Billion,Top_Creator,Top_Creator_Subs_Million,Language_Group,GDP_Per_Capita_USD
16,Russia,Eastern Europe,Russia,Rest of World,146,130,95,1.9,85,News,42,A4,75.0,Russian,14000
17,USA,North America,United States,Rest of World,342,312,246,2.9,93,Entertainment,240,MrBeast,390.0,English,82000
18,Canada,North America,Canada,Rest of World,40,38,31,2.1,92,Education,11,Linus Tech Tips,16.0,English/French,54000
19,Mexico,North America,Mexico,Rest of World,131,104,83,2.7,77,Entertainment,51,Badabun,47.0,Spanish,13000
20,Brazil,South America,Brazil,Rest of World,216,181,144,2.8,81,Music,77,KondZilla,67.0,Portuguese,10300
21,Argentina,South America,Argentina,Rest of World,46,41,33,2.2,82,Gaming,12,VEGETTA777,34.0,Spanish,13700
22,UK,Europe,United Kingdom,Rest of World,69,66,57,2.0,95,Education,18,DanTDM,29.0,English,51000
23,Germany,Europe,Germany,Rest of World,84,79,65,1.8,94,Tech,21,Kurzgesagt,24.0,German,55000
24,France,Europe,France,Rest of World,65,61,52,1.9,92,Lifestyle,18,Squeezie,19.0,French,47000
25,Spain,Europe,Spain,Rest of World,48,45,39,2.1,91,Gaming,14,elrubiusOMG,41.0,Spanish,33000
26,Italy,Europe,Italy,Rest of World,59,54,45,1.7,89,Lifestyle,13,FavijTV,7.0,Italian,39000
27,Nigeria,Africa,Nigeria,Rest of World,229,122,68,2.5,69,Comedy,18,MarkAngelComedy,9.0,English,2400
28,South Africa,Africa,South Africa,Rest of World,63,47,32,2.1,73,Music,10,Waffles,2.0,English,6700
29,Egypt,Africa,Egypt,Rest of World,116,82,55,2.2,71,Entertainment,16,Ahmed Hassan,8.0,Arabic,4300
30,Australia,Oceania,Australia,Rest of World,27,26,22,1.9,96,Lifestyle,8,LazarBeam,22.0,English,65000
31,New Zealand,Oceania,New Zealand,Rest of World,5,5,4,1.8,95,Gaming,1,Shane Dawson,18.0,English,52000
32,Colombia,South America,Colombia,Rest of World,53,43,34,2.4,76,Music,13,Karen Polinesia,27.0,Spanish,6900
33,Chile,South America,Chile,Rest of World,20,18,15,2.0,88,Tech,5,German Garmendia,45.0,Spanish,16000
34,Peru,South America,Peru,Rest of World,35,27,20,2.1,73,Vlogs,7,Andynsane,4.0,Spanish,7200
35,Poland,Europe,Poland,Rest of World,38,34,28,1.8,89,Gaming,9,Blowek,5.0,Polish,22000
36,Netherlands,Europe,Netherlands,Rest of World,18,17,15,1.7,96,Tech,5,NikkieTutorials,14.0,Dutch,61000
37,Sweden,Europe,Sweden,Rest of World,11,11,9,1.9,97,Gaming,4,PewDiePie,110.0,Swedish/English,63000
38,Norway,Europe,Norway,Rest of World,6,6,5,1.7,98,Gaming,2,Noobwork,1.0,Norwegian,89000
39,Kenya,Africa,Kenya,Rest of World,57,34,21,2.0,67,Comedy,6,Thee Pluto,1.0,English/Swahili,2200
40,Morocco,Africa,Morocco,Rest of World,39,31,22,2.0,70,Entertainment,7,Ilyas Elmaliki,2.0,Arabic/French,3900

In [58]:
np.argmax(world_creator['Top_Creator_Subs_Million'])

np.int64(1)

In [66]:
#top creator 
top_creator = world_creator.at[17,'Top_Creator']
Top_youtuber = print(f"The world most famous youtuber is {top_creator} not including the asia with over {int(np.max(world_creator['Top_Creator_Subs_Million']))} million")

The world most famous youtuber is MrBeast not including the asia with over 390 million

In [69]:
conuntries = list(world_creator['Region'])
Country  = print (f'The  number of country participating is 25 and they are {countries}')

The  number of country participating is 25 and they are ['India', 'Indonesia', 'Pakistan', 'Bangladesh', 'Japan', 'South Korea', 'China', 'Philippines', 'Thailand', 'Vietnam', 'Malaysia', 'Nepal', 'Sri Lanka', 'Saudi Arabia', 'UAE', 'Turkey']

In [77]:
#avg monthly views in Rest of the world 
views =int( np.sum(world_creator['Average_Monthly_Views_Billion']))
Avg_views = print(f'The average monthly Views of the Rest of the world is {views} Billion')
Avg_views

The average monthly Views of the Rest of the world is 628 Billion

In [84]:
#Total internet users in the world 
users =int( np.sum(world_creator['Internet_Users_Million']))
Total_internet_users = print(f'Total internet users of the Rest of the world is {users} million')

Total internet users of the Rest of the world is 1614 million

In [89]:
#Total popoultion of 25 countries 
T_population = int(np.sum(world_creator['Population_Million']))
Total_population = print(f'The popultaion of the 25 countries is {T_population} million')

The popultaion of the 25 countries is 1963 million